title: Benjamin Soh # your name (or website title) here
logo: "/images/Photo3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Likes working with numbers and computers.  
  <br><br>
  Data can guide us to make better choices for the future. 
  <br><br>
  <a href="https://www.linkedin.com/in/benjamin-soh-zhen-wei-804988114/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
